### PR TITLE
Strings and arrays of coordinates set Point types

### PR DESCRIPTION
**Pull request by dankreek**
Here's the code I got going for setting point types with atomic values. I added a test for the `TilingSprite` type which demonstrates the usage. If this all works, I can also code up an example and some docs if this works for you.

This addresses #58

### CODE REVIEW

**Comment by dankreek** [comment]
Awesome, thanks!

**Comment by Izzimach** [comment]
Oops, pulled into `master` not `dev` my bad 😞 

It looks like there's some ES6 in the test script? Did `npm run test` work for you?

**Comment by Izzimach** [comment]
Yeah, can't use `() => {}` in ES5.
Should switch tests to ES6 at some point I guess.

**Comment by Izzimach** [comment]
Yeah, if you want to make an example that would be cool. Maybe modify the cupcake example, or build a parallax scroller?

**Comment by Izzimach** [comment]
And thanks! Didn't say it earlier.

**Pull request merged**
