### PR TITLE
Pixijs v3.0.6

### PR DESCRIPTION
**Pull request by netikular**
I worked through the errors I got after updating the package definitions.

However there is still one failing test that I can figure out.  If there is anyone who can help out with trying to figure out why the stage is not getting set that would be great.  I'm going to pull this build into a project I am just starting and as I find other issues I'll address the fixes here.

I am just opening up this PR so others know that someone is trying to get this to work.

This is in reference to issue: #13

### CODE REVIEW

**Comment by Izzimach** [comment]
Thanks for looking into this.

It appears that there isn't an actual 'stage' class anymore, is that correct? In that case, any test that looks for the stage will fail. I guess the test can instead look for the container attached to the view element.

**Comment by netikular** [comment]
You are correct - there is no longer a stage object, just a container object. And the container object does not have the stage class anymore. 

So I changed the method to check to make sure that the object that is created has the renderStage method.  So that at least the test checks to see we are making a ReactPIXI stage object.

Not to sure if this is a good test anymore, but I do think that it makes sense to keep a Root node definition and calling it a stage is as good as any name.

**Comment by Izzimach** [comment]
Yeah, maybe in the future the stage component can be renamed PIXICanvas or something similar, since it actually creates a canvas element for the PIXI renderer.

Good work, I'll pull this in this weekend hopefully.

**Comment by Izzimach** [comment]
Ok, still need to bump version and deploy.

Also not sure what to do about the browserify-shim for PIXI. I think accessing PIXI in the global namespace is still a thing in v3.

**Comment by netikular** [comment]
As far as I know that is still the way of doing it.

**Pull request merged**
