### PR TITLE
Fix "return null" handling to work for both ReactPIXIComponent and ReactDOMComponent

### LINKED ISSUE #85: Render null breaks
Hello

I have so problems with render `null` as the root element of a component. Getting this error "Uncaught (in promise) TypeError: Cannot read property '_idCounter' of undefined". In this case I can't change the logic because it's inside an HOC of recompose (https://github.com/acdlite/recompose).

```
Uncaught (in promise) TypeError: Cannot read property '_idCounter' of undefined
    at ReactDOMEmptyComponent.mountComponent (eval at <anonymous> (index.js:8231), <anonymous>:29:34)
    at Object.mountComponent (eval at <anonymous> (index.js:1539), <anonymous>:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (eval at <anonymous> (index.js:3894), <anonymous>:371:34)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (index.js:3894), <anonymous>:258:21)
    at Object.mountComponent (eval at <anonymous> (index.js:1539), <anonymous>:46:35)
    at Object.mountChildren (eval at <anonymous> (index.js:3990), <anonymous>:238:44)
    at Object.mountAndAddChildren (eval at <anonymous> (index.js:8866), <anonymous>:366:31)
    at ReactReconcileTransaction.perform (eval at <anonymous> (index.js:2087), <anonymous>:140:20)
    at Object.componentDidMount (eval at <anonymous> (index.js:8866), <anonymous>:469:18)
    at eval (eval at <anonymous> (index.js:3894), <anonymous>:265:25)
```

This also triggers the issue.
```js
class Delayed extends Component {
  state = { ready: false };
  componentDidMount() {
    setTimeout(() => this.setState({ ready }, 1000);
  }
  render() {
    return !this.state.ready ? null : <Text />;
  }
}
```

Also broken.
```
const StatlessComponent = ({ value }) => {
  if (!value) return null;
  return <Text text={value} />
};
```

### PR DESCRIPTION
**Pull request by michalochman**
Fixes #85

### CODE REVIEW

**Comment by Izzimach** [comment]
OK, what's a good test for this? Just make a component with `render() {return null;}` ?

**Comment by michalochman** [comment]
I'll try to open an example pull request later today so it's documented.

**Comment by michalochman** [comment]
Added in #95

**Comment by michalochman** [comment]
@Izzimach can you please prepare new release?

**Comment by Izzimach** [comment]
v0.9.14

**Pull request merged**
